name: Train, Test, Code Quality, Build, and Push Docker Image

on:
  push:
    branches:
      - uat

env:
  BRANCH_NAME: ${{ github.ref_name }}
  SHORT_SHA: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/iris-api

jobs:
  train-test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Train the model
        run: python train_model.py

      - name: Run unit tests
        run: pytest

      - name: SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_PROJECT_KEY: your-project-key
          SONAR_ORGANIZATION: your-org-name

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          docker build -t $IMAGE_NAME:latest \
                       -t $IMAGE_NAME:${{ github.ref_name }} \
                       -t $IMAGE_NAME:${{ github.ref_name }}-$SHORT_SHA .

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.ref_name }}
          docker push $IMAGE_NAME:${{ github.ref_name }}-$SHORT_SHA

      - name: Prepare for UAT
        run: |
          echo "Preparing for UAT environment..."
          echo "Trigger UAT pipeline or deploy to staging cluster if needed."