name: Deploy to Minikube on GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GIT_GOOGLE_TOKEN }}'

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-gcp-project-id

    - name: SSH and deploy (inline script)
      run: |
        gcloud compute ssh l00187422@apurva \
          --zone=europe-west2-c \
          --command="touch /home/l00187422/cd.txt"